# [START runtime]
runtime: nodejs12
handlers:
  - url: /
    static_files: dist/schoolauctionfe/index.html
    upload: dist/schoolauctionfe/index.html
  - url: /
    static_dir: dist/schoolauctionfe
# [END runtime]
